### ISSUE TITLE
Number of minhash_bits for 1% relative error for 0.1% similarity.

### ISSUE THREAD

**Issue by kportertx** [yunwilliamyu/hyperminhash#3]
From the paper I need -- minhash_bits > log(6 / (0.001 * 0.01))
```
In [313]: log(6/(0.001 * 0.01))                                                                                                                                           
Out[313]: 13.304684934198283
```
So 16 bits for minhash should be more than adequate? But when I test, the error is significantly higher. What am I missing?

```
seed a n_keys 1048576 mod 999 ratio 0.001 index_bits 16 minhash_bits 16
...
hll - count (      1024       1025          1) intersect          1 target          1 error 2.086
hmh - count (      1024       1025          1) intersect          1 target          1 error 1.578
hll - count (      2048       2046          2) intersect          2 target          2 error 1.823
hmh - count (      2048       2046          2) intersect          2 target          2 error 0.812
hll - count (      4096       4094          4) intersect          4 target          4 error 1.277
hmh - count (      4096       4094          4) intersect          4 target          4 error 0.738
hll - count (      8192       8196          8) intersect          8 target          8 error 0.108
hmh - count (      8192       8196          8) intersect          9 target          8 error 3.890
hll - count (     16384      16385         16) intersect         16 target         16 error 4.372
hmh - count (     16384      16385         16) intersect         17 target         16 error 3.474
hll - count (     32768      32734         32) intersect         32 target         33 error 2.649
hmh - count (     32768      32734         32) intersect         33 target         33 error 0.804
hll - count (     65536      65643         65) intersect         67 target         66 error 2.136
hmh - count (     65536      65643         65) intersect         68 target         66 error 3.868
hll - count (    131072     131252        131) intersect        127 target        131 error 2.898
hmh - count (    131072     131252        131) intersect        150 target        131 error 14.813
hll - count (    262144     263361        263) intersect        204 target        262 error 22.319
hmh - count (    262144     263361        263) intersect        278 target        262 error 6.163
hll - count (    524288     524280        525) intersect        360 target        524 error 31.415
hmh - count (    524288     524280        525) intersect        504 target        524 error 3.837
hll - count (   1048576    1056910       1051) intersect        985 target       1049 error 6.062
hmh - count (   1048576    1056910       1051) intersect       1145 target       1049 error 9.197
```

Test code here: https://github.com/kportertx/hyperminhash/blob/master/test3.py

**Comment by yunwilliamyu** [comment]
Ah, what's going on is that while the number of minhash bits is correct, the number of minhash buckets is not. I think that's actually a bug in the final space bound in the paper. The standard minhash bound of error on the order 1/sqrt(k) is actually an absolute error. So if you're using 2^16 buckets, then the minhash error for the Jaccard index (not even using hyperminhash compression) is going to be on the order of 1/256 ~ 0.004 asymptotically. The analysis in the paper focuses on the number of additional collisions from using hyperminhash compression, but the number of buckets still determines an absolute error in Jaccard index estimation.

Thanks for catching that.

**Comment by kportertx** [comment]
If I understand correctly, 16 index_bits should provide 0.4% **absolute** error when estimating the Jaccard index, correct?

**Comment by kportertx** [comment]
BTW, I believe you meant to use [union_filled_buckets](https://github.com/yunwilliamyu/hyperminhash/blob/master/hyperminhash.py#L253) on line 257.

**Comment by yunwilliamyu** [comment]
Mostly yes. The 16 index_bits for standard MinHash gives a 0.004 standard deviation on the Jaccard index so long as there are no MinHash collisions. (i.e. so with 95% probability, it'll be within 0.8% absolute error, as that's 2 standard deviations).

The analysis in my paper was mostly bounding the _additional_ error that comes from doing a floating point compression on the hash values. So you also need sufficient minhash_bits in order to prevent the floating point compression from adding to the error.

Does that make sense?

Also, thanks for the catch! Yes, I did.

**Comment by kportertx** [comment]
Yes, thank you. I was able to explain my remaining mysteries with the absolute vs relative error confusion. Thanks again for providing a reference implementation, it has been been very helpful to compare against.
